### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### moll/vim-node now has a Chat Room on Gitter

@moll has just created a chat room. You can visit it here: [https://gitter.im/moll/vim-node](https://gitter.im/moll/vim-node?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/moll/vim-node?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by moll** [comment]
Until Gitter has export functionality, it's not a good idea to type text into it. ;)

**Comment by malditogeek** [comment]
@moll we have an API that you can use to export all your messages: https://developer.gitter.im/docs/messages-resource

We'll probably have an Archive exporter to get a nice JSON package with all your messages in the future.

:+1:

**Comment by moll** [comment]
Hehe, sweet of you to answer. I'd love a single button to get that JSON. I don't have the time to build CLI downloaders myself. :( If you guys get one, that'd be great, too (`gitter export moll/vim-node > history.json`) ;)

**Comment by moll** [comment]
I was about to say that hey, nothing more than `curl` necessary, but the OAuth thing is cumbersome for a one-off thing. Could I just do `--user moll:mygitterpasswd` or get a token from some settings page?

**Comment by malditogeek** [comment]
Yeah, if you go to https://developer.gitter.im/apps (you need to be signed in) you'll see a personal access token, works like the ones in GitHub it'll allow to access the API authenticated as yourself.

**Pull request closed without merging**
